import {cloud,currentUser,listProjects,message,escapeHTML as esc} from './cloud.js';
const main=document.querySelector('#account-main');
const raw=new URLSearchParams(location.search).get('return');
const returnTo=raw&&/^\/studio\.html(?:\?|$)/.test(raw)?raw:null;
function login(){main.innerHTML=`<div class="account-auth"><section class="account-story"><span class="eyebrow">IL TUO LABORATORIO DIDATTICO</span><h1>I tuoi magazzini.<br>Un progetto alla volta.</h1><p>Conserva i layout delle esercitazioni e riprendi il lavoro anche da un altro dispositivo.</p><img src="assets/homepage/lab-stoccaggio.jpg" alt="Scaffalature del laboratorio Warehouse Lab"><p>Pianta, attrezzature, merci e percorsi.<br>Riuniti nel tuo archivio personale.</p></section><section class="account-form-card"><span class="eyebrow">WAREHOUSE LAB / ACCOUNT</span><h2>Bentornato.</h2><p>Accedi per salvare e riaprire i tuoi progetti.</p><form id="login-form"><label>Nome utente<input name="username" autocomplete="username" required maxlength="254" placeholder="Il tuo nome utente"></label><label>Password<input name="password" type="password" autocomplete="current-password" required maxlength="128"></label><button class="button" type="submit">Accedi →</button></form><p id="account-status" role="status"></p><a href="studio.html?session=plan">Continua senza accedere ↗</a><small>Senza accesso, i progetti restano sul dispositivo e possono essere esportati come file.</small></section></div>`;
document.querySelector('#login-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;status('Accesso in corso…');try{const f=new FormData(e.target),username=String(f.get('username')).trim();const {error}=await cloud.auth.signInWithPassword({email:username.toLowerCase()==='redazione'?'redazione@example.invalid':username,password:String(f.get('password'))});if(error)throw error;e.target.reset();if(returnTo)location.assign(returnTo);else await archive();}catch(error){status(message(error));button.disabled=false;}};}
function status(s){const target=document.querySelector('#account-status');if(target)target.textContent=s;}
async function archive(){const user=await currentUser();if(!user)return login();main.innerHTML=`<section class="archive-heading"><div><span class="eyebrow">IL TUO ARCHIVIO PERSONALE</span><h1>I miei progetti</h1><p>Riapri un magazzino per continuare il lavoro e confrontarlo in classe.</p></div><a class="button" href="studio.html?session=plan&new=1">+ Nuovo magazzino</a></section><div class="account-toolbar"><span>${esc(user.email==='redazione@example.invalid'?'redazione':user.email)}</span><button id="logout">Esci dall’account</button></div><div class="archive-local"><div><b>Hai già iniziato un progetto?</b><p>Aprilo nell’editor e scegli “Salva online” per aggiungerlo all’archivio.</p></div><a href="studio.html?session=plan">Riprendi sul dispositivo ↗</a></div><div class="archive-controls"><h2>Magazzini salvati</h2><label>Cerca un progetto<input id="search" type="search" placeholder="Nome del magazzino"></label></div><p id="account-status" role="status">Caricamento dei progetti…</p><div id="project-grid"></div>`;
document.querySelector('#logout').onclick=async()=>{const {error}=await cloud.auth.signOut({scope:'local'});if(error)return status(message(error));login();};
try{const projects=await listProjects();const render=()=>{const q=document.querySelector('#search').value.toLocaleLowerCase('it');const filtered=projects.filter(p=>p.name.toLocaleLowerCase('it').includes(q));document.querySelector('#project-grid').innerHTML=filtered.map(p=>`<article class="project-card"><a class="project-cover" href="studio.html?project=${encodeURIComponent(p.id)}" tabindex="-1" aria-hidden="true"><img src="assets/homepage/lab-stoccaggio.jpg" alt=""><span>PROGETTO DI MAGAZZINO</span></a><div><h3>${esc(p.name)}</h3><p>Salvato il ${esc(new Date(p.updated_at).toLocaleString('it-IT',{dateStyle:'medium',timeStyle:'short'}))}</p><a href="studio.html?project=${encodeURIComponent(p.id)}">Apri progetto ↗</a></div></article>`).join('');status(projects.length?`${filtered.length} ${filtered.length===1?"progetto":"progetti"}`:'Il tuo archivio è pronto. Crea un magazzino e salvalo online dall’editor.');};document.querySelector('#search').oninput=render;render();}catch(error){status(message(error));}}
try{if(await currentUser())await archive();else login();}catch{login();status('Connessione non disponibile. Riprova tra poco.');}
