import {createClient} from './vendor/supabase.js';
import {SUPABASE_URL,SUPABASE_KEY} from './cloud-config.js';
import {validate} from './model.js';
export const cloud=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{storageKey:'warehouse-auth-v1',persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});
export const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function message(e){if(e?.code==='invalid_credentials')return 'Nome utente o password non corretti.';if(e?.code==='P0001')return 'Il progetto è stato modificato in un’altra scheda. Riapri la versione online oppure salva come nuova copia.';if(e?.status===429)return 'Troppi tentativi. Attendi qualche minuto e riprova.';return e?.message?.startsWith('Warehouse: ')?e.message.slice(11):'Operazione non riuscita. Controlla la connessione e riprova. La copia locale resta disponibile.';}
export async function currentUser(){const {data,error}=await cloud.auth.getUser();if(error){if(error.name==='AuthSessionMissingError')return null;throw error;}return data.user;}
export async function requireUser(){const user=await currentUser();if(!user)throw Error('Warehouse: Accedi al tuo account per salvare online.');return user;}
export async function listProjects(){await requireUser();const {data,error}=await cloud.from('warehouse_projects').select('id,name,revision,updated_at').order('updated_at',{ascending:false});if(error)throw error;return data;}
export async function loadProject(id){const user=await requireUser();const {data,error}=await cloud.from('warehouse_projects').select('*').eq('id',id).single();if(error)throw Error('Warehouse: Progetto non disponibile per questo account.');return {project:validate(data.document),id:data.id,revision:data.revision,owner:user.id};}
export async function saveProject(project,binding){const user=await requireUser();if(binding&&binding.owner!==user.id)throw Error('Warehouse: Accedi con l’account proprietario oppure salva una nuova copia.');const document=structuredClone(validate(project));document.name=(document.name||'Il mio magazzino').trim()||'Il mio magazzino';if(JSON.stringify(document).length>2e6)throw Error('Warehouse: Il progetto supera il limite di 2 MB.');const id=binding?.id||crypto.randomUUID();const {data,error}=await cloud.rpc('save_warehouse',{project_id:id,expected_revision:binding?.revision||0,project_document:document});if(error)throw error;return {id,owner:user.id,revision:data};}
