export const catalog=[{type:'rack',name:'Scaffalatura',symbol:'▥',w:3,d:1.2,h:4.2},{type:'pallet',name:'Pallet',symbol:'▤',w:1.2,d:.8,h:1},{type:'forklift',name:'Carrello elevatore',symbol:'♧',w:1.3,d:2.6,h:2.2},{type:'pedestrian',name:'Percorso pedonale',symbol:'↟',w:1.5,d:12,h:.025},{type:'vehicle',name:'Corsia mezzi',symbol:'⇄',w:3.5,d:16,h:.025},{type:'shipping',name:'Area spedizioni',symbol:'▱',w:6,d:4,h:.03},{type:'exit',name:'Area uscita',symbol:'⇥',w:2,d:2,h:.03},{type:'bench',name:'Banco imballaggio',symbol:'⊞',w:2,d:1,h:.95}];
catalog.push({type:'worker',name:'Operatore con DPI',symbol:'♙',w:.65,d:.65,h:1.8},{type:'warningSign',name:'Cartello carrelli',symbol:'△',w:.75,d:.55,h:2.2},{type:'exitSign',name:'Cartello uscita',symbol:'→',w:.8,d:.55,h:2.2},{type:'speedSign',name:'Limite 5 km/h',symbol:'⑤',w:.65,d:.55,h:2.2},{type:'barrier',name:'Barriera pedonale',symbol:'⊓',w:2,d:.3,h:1.1});
export const isZone=o=>['pedestrian','vehicle','shipping','exit'].includes(o.type);
export function item(type,x=0,z=0){return {...catalog.find(o=>o.type===type),id:crypto.randomUUID(),x,z,rotation:0};}
export function demo(){const objects=[];for(const x of [-7,-2,3])for(const z of [-6,-2,2])objects.push(item('rack',x,z));objects.push(item('vehicle',7,0),item('pedestrian',-11,0),item('shipping',1,9),item('exit',-11,11),item('forklift',7,5),item('bench',-6,8),item('pallet',0,9),item('pallet',2,9));return {version:1,width:28,depth:26,objects};}
export function legacyWarehouseDemo(){const objects=[];for(const z of [-7,-5.7,0,1.3,7,8.3])for(const x of [-10,-7,-4,-1,2])objects.push(item('rack',x,z));objects.push(Object.assign(item('vehicle',9,-3),{w:4,d:25}),Object.assign(item('pedestrian',-16,0),{d:26}),Object.assign(item('shipping',8,12),{w:10,d:4}),item('exit',-16,14),item('forklift',9,5),item('bench',-6,12),item('bench',-3,12));for(const x of [5,7,9,11])for(const z of [11.2,12.6])objects.push(item('pallet',x,z));objects.push(Object.assign(item('forklift',4,-11),{rotation:90}));return {version:1,width:36,depth:32,objects};}
export function warehouseDemo(){
 const objects=[];
 for(const z of [-12,-10.7,-5,-3.7,2,3.3,9,10.3])for(const x of [-15,-12,-9,-6,-3,0])objects.push(item('rack',x,z));
 objects.push(Object.assign(item('vehicle',9,-3),{w:4,d:30}),Object.assign(item('pedestrian',-21,0),{d:34,w:1.8}),Object.assign(item('shipping',14,16),{w:12,d:4}),item('exit',-21,18),item('forklift',9,5),item('bench',-10,16),item('bench',-6,16));
 for(const x of [10,12,14,16,18])for(const z of [15.2,16.6])objects.push(item('pallet',x,z));
 objects.push(Object.assign(item('forklift',4,-16),{rotation:90}));
 objects.push(item('worker',-21,-7),Object.assign(item('worker',-21,8),{rotation:180}),Object.assign(item('worker',-10,17.2),{rotation:180}),Object.assign(item('worker',-6,17.2),{rotation:180}),item('worker',-18,-16));
 objects.push(item('warningSign',6,-16),item('speedSign',12,-16),item('exitSign',-19.5,18));
 for(const z of [-12,-4,4,12])objects.push(Object.assign(item('barrier',-19.3,z),{rotation:90}));
 return {version:1,width:48,depth:40,objects};
}
export function isLegacyDemo(project){const clean=p=>JSON.stringify({width:p.width,depth:p.depth,objects:p.objects.map(({id,...o})=>o)});return clean(project)===clean(legacyWarehouseDemo());}
export function bounds(o){const turn=o.rotation%180!==0;return {x:o.x,z:o.z,w:turn?o.d:o.w,d:turn?o.w:o.d};}
export function overlap(a,b){a=bounds(a);b=bounds(b);return Math.abs(a.x-b.x)<(a.w+b.w)/2-.01&&Math.abs(a.z-b.z)<(a.d+b.d)/2-.01;}
export function analyze(p){const issues=[];for(const o of p.objects){const b=bounds(o);if(Math.abs(b.x)+b.w/2>p.width/2+.001||Math.abs(b.z)+b.d/2>p.depth/2+.001)issues.push({id:o.id,title:'Elemento fuori dal magazzino',text:`${o.name}: sposta o ridimensiona l’elemento per contenerlo nella superficie.`});}for(let i=0;i<p.objects.length;i++)for(let j=i+1;j<p.objects.length;j++){const a=p.objects[i],b=p.objects[j];if(!overlap(a,b))continue;let solid=!isZone(a)&&!isZone(b);let route=[a,b].find(o=>['pedestrian','exit','vehicle'].includes(o.type));let other=route===a?b:a;if(solid)issues.push({id:a.id,ids:[a.id,b.id],title:'Ingombri sovrapposti',text:`${a.name} e ${b.name} occupano lo stesso spazio. Separa gli elementi.`});else if(route&&!isZone(other)&&!(route.type==='vehicle'&&other.type==='forklift')&&!(route.type==='pedestrian'&&other.type==='worker'))issues.push({id:other.id,ids:[other.id,route.id],title:route.type==='exit'?'Area uscita occupata':'Percorso occupato',text:`${other.name} interferisce con ${route.name.toLowerCase()}. Libera il passaggio.`});else if((a.type==='pedestrian'&&b.type==='vehicle')||(a.type==='vehicle'&&b.type==='pedestrian'))issues.push({id:a.id,ids:[a.id,b.id],title:'Intersezione pedoni / mezzi',text:'I percorsi si incrociano. Valuta separazione, visibilità e gestione dell’attraversamento.'});}return issues;}
export function validate(p){if(!p||p.version!==1||!Number.isFinite(p.width)||!Number.isFinite(p.depth)||p.width<16||p.width>60||p.depth<16||p.depth>60||!Array.isArray(p.objects)||p.objects.length>300)throw Error('Progetto non valido.');if(p.logisticsYard!==undefined&&typeof p.logisticsYard!=='boolean')throw Error('Piazzale non valido.');if(p.name!==undefined&&(typeof p.name!=='string'||p.name.length>100))throw Error('Nome progetto non valido.');const ids=new Set();for(const o of p.objects){if(!catalog.some(c=>c.type===o.type)||typeof o.id!=='string'||ids.has(o.id)||typeof o.name!=='string'||o.name.length>100||!['x','z','w','d','h','rotation'].every(k=>Number.isFinite(o[k]))||Math.abs(o.x)>100||Math.abs(o.z)>100||o.w<.1||o.d<.1||o.w>60||o.d>60||o.h<=0||o.h>12||![0,90,180,270].includes(o.rotation))throw Error('Elemento non valido.');if(o.cargoType!==undefined&&!['cartons','totes','drums','crates'].includes(o.cargoType))throw Error('Tipologia merce non valida.');ids.add(o.id);}return p;}
