import {inspectSimulation} from './simulation-layout.js';
export function mountSimulationGuide({getProject,save,add}){
 const dialog=document.createElement('dialog');dialog.className='editor-help simulation-guide';dialog.innerHTML='<form method="dialog"><button aria-label="Chiudi guida">×</button></form><p class="eyebrow">PROGETTA PER SIMULARE</p><h2>Prepara il tuo magazzino</h2><p>Aggiungi gli elementi, disponili nella pianta e controlla i passaggi. Il percorso simulerà un lotto simbolico nel tuo layout, senza modificare il progetto salvato.</p><p id="guide-progress" role="status"></p><div id="simulation-checks"></div><div id="simulation-problems" role="status"></div><p class="muted">Verifica didattica di ingombri e collegamenti su griglia: non è una certificazione di sicurezza né una verifica delle manovre dei mezzi.</p><button id="launch-simulation" class="primary">Avvia nel mio magazzino →</button>';
 document.body.append(dialog);const trigger=document.createElement('button');trigger.textContent='Guida alla simulazione';document.querySelector('.simple-workflow').append(trigger);
 const open=()=>{refresh();dialog.showModal();};trigger.onclick=open;
 const simulator=document.querySelector('button[onclick*="simulator.html"]');if(simulator){simulator.removeAttribute('onclick');simulator.onclick=open;simulator.textContent='Simula il mio magazzino';}
 function refresh(){const result=inspectSimulation(getProject()),root=dialog.querySelector('#simulation-checks');root.replaceChildren();const next=result.checks.find(c=>!c.ok);dialog.querySelector('#guide-progress').textContent=next?'Prossimo passo: '+next.title+' · '+result.checks.filter(c=>c.ok).length+' di 7 requisiti presenti':'7 di 7 requisiti presenti · verifica del layout';result.checks.forEach((c,i)=>{const row=document.createElement('article'),h=document.createElement('h3'),p=document.createElement('p');h.textContent=`${c.ok?'✓':i+1+'.'} ${c.title}`;p.textContent=c.why;row.append(h,p);if(!c.ok){const b=document.createElement('button');b.textContent='Aggiungi '+c.title.toLowerCase();b.onclick=()=>{dialog.close();add(c.type);};row.append(b);}root.append(row);});const errors=dialog.querySelector('#simulation-problems');errors.replaceChildren();for(const text of result.problems){const p=document.createElement('p');p.textContent=text;errors.append(p);}if(result.ready)errors.textContent='Il layout è pronto per la simulazione.';dialog.querySelector('#launch-simulation').disabled=!result.ready;return result;}
 dialog.querySelector('#launch-simulation').onclick=()=>{if(!refresh().ready)return;try{save();const id=crypto.randomUUID();sessionStorage.setItem('warehouse-simulation-'+id,JSON.stringify({project:getProject(),returnTo:location.pathname+location.search}));location.assign('simulator.html?layout='+id);}catch{dialog.querySelector('#simulation-problems').textContent='Impossibile preparare la simulazione. Esporta il progetto e verifica lo spazio disponibile nel browser.';}};
 return {open,refresh:()=>{if(dialog.open)refresh();}};
}
