import {createEquipment,isEquipment} from './equipment-models.js';
import {createTruckYard} from './truck-yard.js';
import {createHumanWorker,animateHuman} from './human-worker.js';
import * as T from 'three';
import { OrbitControls } from './vendor/OrbitControls.js';
import { RoomEnvironment } from './vendor/addons/environments/RoomEnvironment.js';
import { RoundedBoxGeometry } from './vendor/addons/geometries/RoundedBoxGeometry.js';
import { mergeGeometries } from './vendor/addons/utils/BufferGeometryUtils.js';
import { EffectComposer } from './vendor/addons/postprocessing/EffectComposer.js';
import { SSAOPass } from './vendor/addons/postprocessing/SSAOPass.js';
import { OutputPass } from './vendor/addons/postprocessing/OutputPass.js';
import { RenderPass } from './vendor/addons/postprocessing/RenderPass.js';
import { ShaderPass } from './vendor/addons/postprocessing/ShaderPass.js';
import { FXAAShader } from './vendor/addons/shaders/FXAAShader.js';
import { UnrealBloomPass } from './vendor/addons/postprocessing/UnrealBloomPass.js';
import { vehicleRoute, workerRoute, routePosition, routeEnvelope, routesIntersect } from './motion.js';
import { WarehouseAtmosphere, lightingPresets } from './atmosphere.js';

// Shared geometry/material pools and per-object batching keep the detailed scene manageable.
const geometries=new Map(),materials=new Map(),textureCache=new Map();
const palette={steel:'#234f73',beam:'#d66725',metal:'#737f87',rubber:'#24292c',yellow:'#e8b437',wood:'#bba17b',wall:'#c4cace',dark:'#263039',white:'#ebece5'};
function mat(color,rough=.65,metal=0){const key=`${color}|${rough}|${metal}`;if(!materials.has(key))materials.set(key,new T.MeshStandardMaterial({color:palette[color]||color,roughness:rough,metalness:metal}));return materials.get(key);}
function geometry(key,create){if(!geometries.has(key))geometries.set(key,create());return geometries.get(key);}
function add(g,geo,m,x=0,y=0,z=0){const mesh=new T.Mesh(geo,typeof m==='string'?mat(m):m);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;g.add(mesh);return mesh;}
function box(g,w,h,d,x,y,z,m){return add(g,geometry('cube',()=>new T.BoxGeometry(1,1,1)),m,x,y,z).scale.set(w,h,d);}
function rounded(g,w,h,d,x,y,z,m,r=.07){const mesh=add(g,geometry(`round:${w},${h},${d},${r}`,()=>new RoundedBoxGeometry(w,h,d,2,r)),m,x,y,z);return mesh;}
function cyl(g,r,h,x,y,z,m,r2=r){return add(g,geometry(`c:${r}:${r2}:${h}`,()=>new T.CylinderGeometry(r,r2,h,12)),m,x,y,z);}
function rod(g,a,b,r,m){const v1=new T.Vector3(...a),v2=new T.Vector3(...b),delta=v2.clone().sub(v1);const mesh=cyl(g,r,delta.length(),...v1.clone().add(v2).multiplyScalar(.5).toArray(),m);mesh.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),delta.normalize());return mesh;}
function batch(g){g.updateMatrixWorld(true);const buckets=new Map(),remove=[];g.traverse(o=>{if(o.isMesh&&!o.userData.keep){if(!buckets.has(o.material))buckets.set(o.material,[]);const geo=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();buckets.get(o.material).push(geo.applyMatrix4(o.matrixWorld));remove.push(o);}});for(const o of remove)o.removeFromParent();for(const [material,list]of buckets){const geo=mergeGeometries(list,false);list.forEach(g=>g.dispose());if(!geo)continue;const m=add(g,geo,material);m.userData.owned=true;}return g;}
function canvasTexture(key,draw,w=512,h=256){if(textureCache.has(key))return textureCache.get(key);const c=document.createElement('canvas');c.width=w;c.height=h;draw(c.getContext('2d'),w,h);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;t.anisotropy=8;textureCache.set(key,t);return t;}
function sign(g,text,w,h,x,y,z,bg='#203d50',fg='#fff',rotation=0){const tex=canvasTexture(`sign:${text}:${bg}:${fg}`,(c,W,H)=>{c.fillStyle=bg;c.fillRect(0,0,W,H);c.strokeStyle=fg;c.lineWidth=5;c.strokeRect(12,12,W-24,H-24);c.fillStyle=fg;c.textAlign='center';c.textBaseline='middle';c.font='600 90px Arial';c.fillText(text,W/2,H/2,W-45);});const key='signmat:'+text+bg+fg;if(!materials.has(key))materials.set(key,new T.MeshStandardMaterial({map:tex,roughness:.7,side:T.DoubleSide}));const mesh=add(g,geometry('plane',()=>new T.PlaneGeometry(1,1)),materials.get(key),x,y,z);mesh.scale.set(w,h,1);mesh.rotation.y=rotation;return mesh;}
function groundText(g,text,w,d,x,z,bg='#00000000',fg='#dedbbd'){const mesh=sign(g,text,w,d,x,.025,z,bg,fg);mesh.rotation.set(-Math.PI/2,0,0);mesh.material.transparent=true;return mesh;}
const cargoMap=canvasTexture('cargo',(c,W,H)=>{c.fillStyle='#b9a17a';c.fillRect(0,0,W,H);let seed=41;for(let i=0;i<20000;i++){seed=(seed*16807)%2147483647;c.fillStyle=`rgba(60,42,20,${(seed%5)/80})`;c.fillRect(seed%W,(seed*7)%H,1,1);}c.fillStyle='#c8b28c';c.fillRect(W*.47,0,W*.065,H);c.fillStyle='#efede2';c.fillRect(24,36,145,92);c.fillStyle='#3d4242';c.font='bold 15px Arial';c.fillText('LOGISTICS',33,57);c.font='10px monospace';c.fillText('LOT 024 / EURO',33,75);for(let i=0;i<43;i++){c.fillRect(33+i*2.7,84,1+(i%2),27);}c.strokeStyle='#6e614c';c.strokeRect(5,5,W-10,H-10);c.font='28px Arial';c.fillStyle='#554e43';c.fillText('↑↑  ◇',W-110,H-25);});
const carton=new T.MeshStandardMaterial({map:cargoMap,roughness:.93});
function pallet(g,x,y,z,loaded=true,variant=0){
 const pg=new T.Group();g.add(pg);
 for(const zz of [-.33,0,.33])for(const xx of [-.48,0,.48])box(pg,.16,.09,.14,xx,.07,zz,woodMaterial||mat('wood'));
 for(const zz of [-.32,0,.32])box(pg,1.2,.027,.14,0,.014,zz,woodMaterial||mat('wood'));
 for(let i=0;i<5;i++)box(pg,1.2,.024,.12,0,.135,-.32+i*.16,woodMaterial||mat('wood'));
 if(loaded&&variant===99){for(let y=.25;y<1.1;y+=.16){box(pg,1.12,.14,.04,0,y,.36,'wood');box(pg,1.12,.14,.04,0,y,-.36,'wood');box(pg,.04,.14,.7,-.54,y,0,'wood');box(pg,.04,.14,.7,.54,y,0,'wood');}for(const xx of [-.4,.4]){box(pg,.06,.92,.76,xx,.64,0,'#7b644b');}box(pg,1.14,.04,.74,0,1.13,0,'wood');
 }else if(loaded&&variant%7===4){
  // Returnable plastic totes, with rims and recessed handles.
  for(let level=0;level<3;level++)for(const xx of [-.29,.29]){
   box(pg,.53,.27,.7,xx,.285+level*.28,0,mat('#627c87',.48));
   box(pg,.56,.035,.74,xx,.425+level*.28,0,mat('#91a5ab',.45));
   box(pg,.19,.042,.012,xx,.36+level*.28,.356,'dark');
   sign(pg,'B / 042',.2,.075,xx,.25+level*.28,.356,'#cbd0c8','#35464c');
  }
 }else if(loaded&&variant%7===5){
  for(const xx of [-.29,.29]){cyl(pg,.24,.78,xx,.55,0,mat('#567780',.4,.3));for(const yy of [.22,.44,.8,.94])cyl(pg,.247,.025,xx,yy,0,mat('#839b9e',.4,.5));cyl(pg,.045,.012,xx+.11,.947,.07,'dark');sign(pg,'LOT 18',.22,.14,xx,.6,.238,'#eee9d5','#35464c');}
 }else if(loaded){
  const rows=variant%3===0?2:3;
  for(let l=0;l<rows;l++)for(let xx=0;xx<2;xx++)for(let zz=0;zz<2;zz++)box(pg,.54,.3,.34,-.29+xx*.58,.3+l*.305,-.19+zz*.38,carton);
  if(variant%3===1)for(const xx of [-.34,.34])box(pg,.024,rows*.305+.02,.765,xx,.15+rows*.305/2,0,'#4c5660');
  if(variant%7===3){
   // Thin horizontal film seams provide packing detail without heavy glass shaders.
   for(let yy=.23;yy<1;yy+=.12){box(pg,1.13,.012,.006,0,yy,.365,'#d1c7ae');box(pg,1.13,.012,.006,0,yy,-.365,'#d1c7ae');}
  }
 }
 pg.position.set(x,y,z);return pg;
}
let woodMaterial;
const cargoVariant=(o,seed)=>({cartons:1,totes:4,drums:5,crates:99}[o.cargoType]??seed);
function rack(o,index){const g=new T.Group(),w=3,d=1.2,h=4.6;for(const x of [-1.43,1.43]){for(const z of [-.54,.54]){box(g,.095,h,.085,x,h/2,z,mat('steel',.35,.65));box(g,.23,.025,.22,x,.015,z,'metal');for(let y=.3;y<4.5;y+=.28)box(g,.018,.055,.006,x,y,z+.046,'#0a253c');}for(let y=.35;y<4.1;y+=.95){rod(g,[x,y,-.52],[x,y+.85,.52],.017,'metal');rod(g,[x,y+.85,-.52],[x,y,.52],.017,'metal');}box(g,.19,.5,.18,x,.25,.55,'yellow');for(let i=0;i<3;i++){const stripe=add(g,geometry('cube',()=>new T.BoxGeometry(1,1,1)),mat('dark'),x,.12+i*.13,.651);stripe.scale.set(.19,.048,.01);stripe.rotation.z=-.35;}}
for(let level=0;level<3;level++){const y=.28+level*1.4;for(const z of [-.55,.55])box(g,2.84,.14,.07,0,y,z,mat('beam',.4,.45));for(let i=0;i<5;i++)box(g,.035,.05,1.07,-1.2+i*.6,y,0,'metal');for(const x of [-.72,.72]){const slot=level*2+(x>0?1:0);if(!o.cargoSlots||o.cargoSlots[slot])pallet(g,x,y+.085,0,true,cargoVariant(o.cargoSlots?{cargoType:o.cargoSlots[slot]}:o,index+level+(x>0?1:0)));}sign(g,`A${String(index+1).padStart(2,'0')} · 0${level+1}`,.43,.105,.9,y,.598,'#e3e8e9','#223745');}
sign(g,`A${String(index+1).padStart(2,'0')}`,.65,.34,0,4.38,.58,'#254f72');batch(g);g.scale.set(o.w/3,o.h/4.6,o.d/1.2);return g;}
function forklift(o){const g=new T.Group();g.userData.wheels=[];rounded(g,1.05,.58,1.23,0,.62,.38,mat('#d89b20',.28,.3),.15);rounded(g,1.12,.5,.4,0,.61,.99,mat('#d7a22e',.35,.4),.12);box(g,1.05,.11,1.2,0,.36,.26,'dark');for(const x of [-.54,.54])for(const z of [-.45,.78]){let m=cyl(g,.27,.18,x,.28,z,'rubber');m.rotation.z=Math.PI/2;m.userData.keep=true;g.userData.wheels.push(m);m=cyl(g,.14,.19,x,.28,z,mat('metal',.28,.7));m.rotation.z=Math.PI/2;m.userData.keep=true;g.userData.wheels.push(m);m=cyl(g,.055,.2,x,.28,z,'dark');m.rotation.z=Math.PI/2;m.userData.keep=true;g.userData.wheels.push(m);}
for(const x of [-.46,.46])for(const z of [-.23,.8])box(g,.052,1.48,.052,x,1.3,z,mat('dark',.35,.65));box(g,1.05,.07,1.24,0,2.03,.29,'dark');for(let z=-.22;z<.85;z+=.2)box(g,.96,.035,.05,0,2.08,z,'dark');rounded(g,.46,.12,.4,0,1.02,.45,'rubber',.05);rounded(g,.46,.5,.12,0,1.23,.63,'rubber',.04);rod(g,[0,.7,-.06],[0,1.25,-.16],.025,'dark');const steering=add(g,geometry('steering',()=>new T.TorusGeometry(.15,.018,8,20)),mat('rubber'),0,1.27,-.16);steering.rotation.x=-.6;
for(const x of [-.38,.38]){box(g,.1,2.28,.1,x,1.15,-.7,'dark');box(g,.052,1.9,.055,x,1.16,-.77,mat('metal',.2,.8));box(g,.115,.055,.82,x,.15,-1.07,'metal');box(g,.1,.68,.06,x,.46,-.68,'metal');}box(g,.86,.12,.09,0,.78,-.78,'dark');rod(g,[0,.33,-.72],[0,1.89,-.72],.043,'metal');for(const x of [-.49,.49])box(g,.12,.1,.04,x,1.72,-.28,'white');const beaconMaterial=new T.MeshStandardMaterial({color:'#ffb329',emissive:'#ff8b10',emissiveIntensity:2});const beacon=cyl(g,.055,.09,.4,2.16,.68,beaconMaterial);beacon.userData.keep=true;beacon.userData.uniqueMaterial=true;g.userData.beacon=beacon;sign(g,'E 25',.5,.16,0,.74,1.205,'#d39e2d','#24303a');batch(g);g.scale.set(o.w/1.3,o.h/2.2,o.d/2.6);return g;}
function workbench(o){const g=new T.Group();box(g,2,.08,1,0,.96,0,woodMaterial||mat('wood'));for(const x of [-.9,.9])for(const z of [-.4,.4])box(g,.055,.94,.055,x,.47,z,'metal');box(g,1.84,.04,.8,0,.26,0,'metal');box(g,.5,.45,.45,-.5,1.21,0,carton);box(g,.36,.035,.28,.5,1.025,.15,'dark');box(g,.06,.3,.06,.55,1.12,-.25,'dark');box(g,.4,.25,.045,.55,1.34,-.23,'dark');box(g,.35,.2,.006,.55,1.35,-.2,'#739fab');cyl(g,.13,.3,.15,1.15,-.25,'#dbd6c0');batch(g);g.scale.set(o.w/2,o.h/.95,o.d);return g;}
const worker=createHumanWorker;
function safetySign(o){const g=new T.Group();rounded(g,.5,.055,.45,0,.03,0,'dark',.025);cyl(g,.028,1.85,0,.94,0,'metal');box(g,.72,.64,.04,0,1.88,0,'metal');
 const tex=canvasTexture('pictogram:'+o.type,(c,W,H)=>{c.fillStyle='#f7f7ed';c.fillRect(0,0,W,H);c.textAlign='center';c.textBaseline='middle';c.lineWidth=12;
 if(o.type==='warningSign'){c.fillStyle='#f7cc35';c.strokeStyle='#17282e';c.beginPath();c.moveTo(W/2,20);c.lineTo(W-55,H-95);c.lineTo(55,H-95);c.closePath();c.fill();c.stroke();c.fillStyle='#17282e';c.fillRect(190,200,95,65);c.fillRect(255,130,18,95);c.fillRect(280,150,12,135);c.fillRect(280,280,55,10);for(const x of [207,265]){c.beginPath();c.arc(x,275,17,0,7);c.fill();}c.font='bold 35px Arial';c.fillText('CARRELLI IN TRANSITO',W/2,H-43,W-35);}
 else if(o.type==='speedSign'){c.strokeStyle='#c84634';c.beginPath();c.arc(W/2,205,155,0,7);c.stroke();c.fillStyle='#1b2e35';c.font='bold 220px Arial';c.fillText('5',W/2,210);c.font='bold 44px Arial';c.fillText('km/h',W/2,H-55);}
 else{c.fillStyle='#2b805a';c.fillRect(0,0,W,H);c.strokeStyle='#fff';c.fillStyle='#fff';c.lineWidth=17;c.strokeRect(55,90,110,230);c.beginPath();c.arc(220,112,25,0,7);c.fill();c.beginPath();c.moveTo(218,152);c.lineTo(192,232);c.lineTo(255,285);c.lineTo(240,345);c.moveTo(193,232);c.lineTo(160,320);c.moveTo(210,176);c.lineTo(275,205);c.moveTo(320,220);c.lineTo(455,220);c.moveTo(410,175);c.lineTo(455,220);c.lineTo(410,265);c.stroke();c.font='bold 44px Arial';c.fillText('USCITA',W/2,H-45);}
 },512,448);
 const key='pictogram-material:'+o.type;if(!materials.has(key))materials.set(key,new T.MeshStandardMaterial({map:tex,roughness:.65,side:T.DoubleSide}));
 const face=add(g,geometry('plane',()=>new T.PlaneGeometry(1,1)),materials.get(key),0,1.88,.025);face.scale.set(.7,.62,1);batch(g);g.scale.set(o.w/.75,o.h/2.2,o.d/.55);return g;
}
function barrier(o){const g=new T.Group();for(const x of [-.9,.9]){cyl(g,.055,1.05,x,.55,0,'yellow');box(g,.24,.05,.3,x,.025,0,'dark');for(const y of [.25,.55,.85])cyl(g,.058,.1,x,y,0,'dark');}for(const y of [.45,1])rod(g,[-.9,y,0],[.9,y,0],.045,'yellow');batch(g);g.scale.set(o.w/2,o.h/1.1,o.d/.3);return g;}
function zone(o){const g=new T.Group(),colors={pedestrian:'#498a76',vehicle:'#c6a443',shipping:'#5e8192',exit:'#458268',receiving:'#4b8e9c',returns:'#b98b51'},color=colors[o.type];const m=new T.MeshStandardMaterial({color,roughness:.94,transparent:true,opacity:o.type==='vehicle'?.14:.35,depthWrite:false});const surface=add(g,geometry('cube',()=>new T.BoxGeometry(1,1,1)),m,0,.008,0);surface.scale.set(o.w,.008,o.d);surface.userData.uniqueMaterial=true;for(const x of [-o.w/2+.035,o.w/2-.035])box(g,.055,.006,o.d,x,.018,0,o.type==='pedestrian'?'#d4ddd0':'#dbc064');for(const z of [-o.d/2+.035,o.d/2-.035])box(g,o.w,.006,.055,0,.018,z,'#dbc064');if(o.type==='vehicle'){for(let z=-o.d/2+1.5;z<o.d/2;z+=3){box(g,.055,.006,1,0,.022,z,'#ded3a1');}for(const x of [-o.w*.23,o.w*.23]){const arrow=groundText(g,x<0?'↑':'↓',.55,1.3,x,0,'#00000000','#e1d5a4');arrow.position.y=.028;}}
if(o.type==='pedestrian'){for(let z=-o.d/2+1;z<o.d/2;z+=3)groundText(g,'↑',.4,.8,0,z,'#00000000','#d8e5d9');}if(o.type==='exit'){for(let z=-o.d/2+.12;z<o.d/2;z+=.27){const mesh=add(g,geometry('cube',()=>new T.BoxGeometry(1,1,1)),mat('#dcc477'),0,.022,z);mesh.scale.set(o.w*.8,.008,.075);}}
groundText(g,{pedestrian:'PEDONI',vehicle:'TRANSITO',shipping:'STAGING 01',exit:'USCITA',receiving:'RICEVIMENTO',returns:'CONTROLLO / RESI'}[o.type],Math.min(o.w*.85,4),.5,0,-o.d/2+.5,'#00000000','#dce0d0');return g;}

export class WarehouseScene{
async previews(specs,onPreview=()=>{}){const renderer=new T.WebGLRenderer({antialias:true,alpha:false});renderer.setSize(256,168);renderer.setPixelRatio(1);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;const scene=new T.Scene();scene.background=new T.Color('#dbe3d6');scene.environment=this.scene.environment;scene.environmentIntensity=.4;scene.add(new T.HemisphereLight('#ffffff','#7a8792',2));const light=new T.DirectionalLight('#fff3da',3);light.position.set(-3,7,5);scene.add(light);const cam=new T.PerspectiveCamera(36,256/168,.1,60),result={};for(const o of specs){await new Promise(resolve=>requestAnimationFrame(()=>setTimeout(resolve,0)));let g;if(isEquipment(o.type))g=createEquipment(o);else if(o.type==='rack')g=rack(o,0);else if(o.type==='forklift')g=forklift(o);else if(o.type==='bench')g=workbench(o);else if(o.type==='worker')g=worker(o);else if(o.type==='barrier')g=barrier(o);else if(o.type.endsWith('Sign'))g=safetySign(o);else if(o.type==='pallet'){g=new T.Group();pallet(g,0,0,0,true,1);batch(g);}else{g=zone({...o,w:2.5,d:3.5});}scene.add(g);const b=new T.Box3().setFromObject(g),c=b.getCenter(new T.Vector3()),s=b.getSize(new T.Vector3()),dist=Math.max(s.x,s.y,s.z)*1.7;cam.position.set(c.x+dist*.8,c.y+dist*.6,c.z+dist);cam.lookAt(c);renderer.render(scene,cam);result[o.type]=renderer.domElement.toDataURL('image/png');onPreview(o.type,result[o.type]);scene.remove(g);g.traverse(m=>{if(m.userData.owned)m.geometry.dispose();if(m.userData.uniqueMaterial)m.material.dispose();});}renderer.dispose();return result;}
constructor(container,onSelect){this.container=container;this.onSelect=onSelect;this.mode='3d';this.motionEnabled=!matchMedia('(prefers-reduced-motion: reduce)').matches;this.motionTime=0;this.movers=[];this.people=[];this.lastFrame=null;this.scene=new T.Scene();this.scene.background=new T.Color('#36434b');this.scene.fog=new T.Fog('#36434b',95,180);this.renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.0;container.prepend(this.renderer.domElement);this.camera=new T.PerspectiveCamera(43,1,.1,220);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.dampingFactor=.075;this.controls.minDistance=1.3;this.controls.maxDistance=210;this.controls.maxPolarAngle=Math.PI*.49;this.controls.target.set(0,1,0);
const env=new RoomEnvironment(),pmrem=new T.PMREMGenerator(this.renderer);this.envTarget=pmrem.fromScene(env,.04);this.scene.environment=this.envTarget.texture;this.scene.environmentIntensity=.32;env.dispose();pmrem.dispose();this.ambient=new T.HemisphereLight('#d5e8ff','#7c858e',.48);this.scene.add(this.ambient);this.sun=new T.DirectionalLight('#ffe9cc',2.0);this.sun.position.set(-20,35,18);this.sun.castShadow=true;this.sun.shadow.mapSize.set(2048,2048);this.sun.shadow.bias=-.00018;this.sun.shadow.normalBias=.035;Object.assign(this.sun.shadow.camera,{left:-38,right:38,top:38,bottom:-38,near:1,far:100});this.scene.add(this.sun);const fill=new T.DirectionalLight('#b8d3fa',.8);fill.position.set(15,20,-20);this.scene.add(fill);this.fill=fill;this.atmosphere=new WarehouseAtmosphere(this.scene);
this.composer=new EffectComposer(this.renderer);this.composer.addPass(new RenderPass(this.scene,this.camera));this.ao=new SSAOPass(this.scene,this.camera,800,600);this.ao.kernelRadius=.7;this.ao.minDistance=.002;this.ao.maxDistance=.12;this.composer.addPass(this.ao);this.bloom=new UnrealBloomPass(new T.Vector2(800,600),.2,.35,1.1);this.composer.addPass(this.bloom);this.composer.addPass(new OutputPass());this.fxaa=new ShaderPass(FXAAShader);this.composer.addPass(this.fxaa);this.root=new T.Group();this.scene.add(this.root);this.selectable=[];this.textureLoader=new T.TextureLoader();this.concrete=this.loadPBR('concrete',8);this.concrete.color.set('#8d979e');woodMaterial=this.loadPBR('wood',1);woodMaterial.color.set('#cfb48d');woodMaterial.normalScale.set(.35,.35);
this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(container);this.ray=new T.Raycaster();this.pointer=new T.Vector2();let down;this.renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);this.renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=this.renderer.domElement.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.ray.setFromCamera(this.pointer,this.camera);const hits=this.ray.intersectObjects(this.selectable,false);if(hits.length)this.setMotion(false,true);onSelect(hits[0]?.object.userData.id||null);});this.needsRender=true;this.controls.addEventListener('change',()=>this.needsRender=true);this.renderer.setAnimationLoop(now=>{const dt=this.lastFrame===null?0:Math.min((now-this.lastFrame)/1000,.08);this.lastFrame=now;if(document.hidden)return;const changed=this.controls.update();this.flowLesson?.update(dt);if(this.motionEnabled&&(this.movers.length||this.people.length||this.yard)){this.motionTime+=dt;this.animateVehicles();this.animatePeople();this.animateTruck();this.needsRender=true;}if((changed||this.needsRender)&&(!this.motionEnabled||!this.lastRendered||now-this.lastRendered>=32)){this.composer.render();this.needsRender=false;this.lastRendered=now;}});}
loadPBR(name,repeat){const maps={};for(const [key,file]of [['map','color'],['normalMap','normal'],['roughnessMap','roughness']]){const t=this.textureLoader.load(`./assets/${name}/${file}.webp`,()=>{this.needsRender=true;});t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(repeat,repeat);t.anisotropy=Math.min(8,this.renderer.capabilities.getMaxAnisotropy());if(key==='map')t.colorSpace=T.SRGBColorSpace;maps[key]=t;}return new T.MeshStandardMaterial({...maps,roughness:.86,normalScale:new T.Vector2(.5,.5)});}
resize(){this.needsRender=true;const w=this.container.clientWidth,h=this.container.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h);this.composer.setSize(w,h);this.fxaa.material.uniforms.resolution.value.set(1/(w*this.renderer.getPixelRatio()),1/(h*this.renderer.getPixelRatio()));const previousAspect=this.camera.aspect;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();if(this.project&&this.mode!=='inside'){const scale=Math.max(1,1/this.camera.aspect)/Math.max(1,1/previousAspect);const offset=this.camera.position.clone().sub(this.controls.target).multiplyScalar(scale);this.camera.position.copy(this.controls.target).add(offset);this.controls.update();}}
clear(){this.root.traverse(o=>{if(o.userData.maps)o.userData.maps.forEach(t=>t.dispose());if(o.isLight)o.dispose();if(o.isSkinnedMesh)o.skeleton.dispose();if(o.userData.owned)o.geometry?.dispose();if(o.userData.uniqueMaterial)o.material?.dispose();});this.scene.remove(this.root);this.root=new T.Group();this.scene.add(this.root);this.selectable=[];}
build(project,selected){this.needsRender=true;this.project=project;this.scene.fog.near=project.logisticsYard?210:95;this.scene.fog.far=project.logisticsYard?380:180;this.camera.far=420;this.camera.updateProjectionMatrix();this.movers=[];this.people=[];this.motionTime=0;this.clear();this.shell(project);this.yard=project.logisticsYard?createTruckYard(project):null;if(this.yard){this.root.add(this.yard.root);this.animateTruck();}this.atmosphere.build(project);this.setLighting(this.atmosphere.mode);project.objects.forEach((o,i)=>{let g;if(isEquipment(o.type))g=createEquipment(o);else if(o.type==='rack')g=rack(o,i);else if(o.type==='forklift')g=forklift(o);else if(o.type==='bench')g=workbench(o);else if(o.type==='worker')g=worker(o);else if(o.type==='barrier')g=barrier(o);else if(o.type.endsWith('Sign'))g=safetySign(o);else if(o.type==='pallet'){g=new T.Group();pallet(g,0,0,0,true,cargoVariant(o,i));batch(g);g.scale.set(o.w/1.2,o.h/1.065,o.d/.8);}else g=zone(o);g.position.set(o.x,0,o.z);g.rotation.y=-o.rotation*Math.PI/180;g.traverse(m=>{if(m.isMesh){m.userData.id=o.id;this.selectable.push(m);}});this.root.add(g);if(o.type==='worker'){const route=workerRoute(project,o),packing=project.objects.some(b=>b.type==='bench'&&Math.hypot(b.x-o.x,b.z-o.z)<2);this.people.push({object:o,group:g,route,packing,phase:i*1.7});}if(o.type==='forklift'){const route=this.movers.length<4?vehicleRoute(project,o):null;if(route&&!this.movers.some(m=>routesIntersect(routeEnvelope(route,o),routeEnvelope(m.route,m.object)))){this.movers.push({object:o,group:g,route,last:{x:o.x,z:o.z}});const headlight=new T.SpotLight('#eef3ff',9,8,.55,.6,2);headlight.position.set(0,1.65,-.35);headlight.target.position.set(0,.03,-4);g.add(headlight,headlight.target);}}if(selected===o.id){const edges=new T.LineSegments(new T.EdgesGeometry(new T.BoxGeometry(o.w+.08,Math.max(o.h,.1)+.08,o.d+.08)),new T.LineBasicMaterial({color:'#ffce6d',transparent:true,opacity:.9,depthTest:false}));edges.userData.owned=true;edges.userData.uniqueMaterial=true;edges.position.set(o.x,Math.max(o.h,.1)/2,o.z);edges.rotation.y=g.rotation.y;edges.renderOrder=100;this.root.add(edges);}});this.flowLesson?.build(project);this.updateMode();this.onMotionChange?.();}
shell(p){const w=p.width,d=p.depth,h=7.5,g=new T.Group();box(g,w+.4,.3,d+.4,0,-.17,0,this.concrete);box(g,w+.42,.13,d+.42,0,-.36,0,'#3d454c');for(let x=-w/2+5;x<w/2;x+=5)box(g,.018,.006,d,x,-.013,0,'#8a9090');for(let z=-d/2+5;z<d/2;z+=5)box(g,w,.006,.018,0,-.012,z,'#8a9090');
// North facade: dock recesses, sectional doors, concrete base and sandwich panels.
box(g,w,h,.2,0,h/2,-d/2,'wall');box(g,w,.8,.24,0,.4,-d/2+.03,'#909b9f');for(let x=-w/2+.5;x<w/2;x+=.5)box(g,.025,h-.85,.028,x,(h+.85)/2,-d/2+.12,'#afb8bc');
for(let i=0;i<3;i++){const x=(i-1)*Math.min(7,w/4),z=-d/2+.2;box(g,4.5,4.75,.2,x,2.375,z,'#3b454d');box(g,3.65,4.08,.1,x,2.07,z+.15,'#879298');for(let y=.23;y<4.1;y+=.32)box(g,3.62,.018,.015,x,y,z+.21,'#5f6b73');box(g,3.5,.75,.03,x,2.9,z+.22,'#344653');for(let xx=-1.35;xx<1.6;xx+=.9)box(g,.025,.7,.018,x+xx,2.9,z+.25,'#7f969f');for(const xx of [-2.04,2.04]){box(g,.26,4.5,.3,x+xx,2.25,z+.22,'rubber');cyl(g,.085,1,x+xx,.5,z+1,'yellow');cyl(g,.09,.16,x+xx,.7,z+1,'dark');}sign(g,'0'+(i+1),1,.56,x,5.13,z+.15,'#263c4b','#f1c065');box(g,3.6,.055,1.35,x,.023,z+.76,'#505e66');}
// East facade with structural columns, high glazing and industrial services.
box(g,.18,h,d,w/2,h/2,0,'wall');box(g,.22,.8,d,w/2-.03,.4,0,'#909b9f');for(let z=-d/2+.5;z<d/2;z+=.5)box(g,.028,h-.85,.025,w/2-.12,(h+.85)/2,z,'#adb7bc');for(let z=-d/2+3;z<d/2-1;z+=5){box(g,.24,1.3,3.8,w/2-.15,5.9,z,'#67818e');for(let zz=-1.8;zz<=1.8;zz+=.9)box(g,.26,1.35,.045,w/2-.18,5.9,z+zz,'#d3d9d8');}
for(let x=-w/2+.3;x<=w/2;x+=6){box(g,.22,h,.28,x,h/2,-d/2+.25,'#697782');box(g,.39,.08,.48,x,.04,-d/2+.25,'metal');}for(let z=-d/2+.3;z<=d/2;z+=6)box(g,.28,h,.22,w/2-.25,h/2,z,'#697782');box(g,w,.25,.16,0,h-.3,-d/2+.25,'metal');box(g,.16,.25,d,w/2-.25,h-.3,0,'metal');rod(g,[-w/2+1,6.45,-d/2+.4],[w/2-.4,6.45,-d/2+.4],.045,'#ba483b');rod(g,[w/2-.4,6.45,-d/2+.4],[w/2-.4,6.45,d/2-.5],.045,'#ba483b');
sign(g,'MAGAZZINO / RICEVIMENTO',6,.65,-w/2+5,6,-d/2+.2,'#c1cace','#314452');const exitX=-w/2+1.4;box(g,1.3,2.5,.15,exitX,1.25,-d/2+.2,'#43736b');box(g,.7,.045,.1,exitX,1.05,-d/2+.32,'metal');sign(g,'USCITA →',1.35,.35,exitX,2.85,-d/2+.28,'#177257');cyl(g,.1,.55,-w/2+2.5,1,-d/2+.35,'#bf3d2e');sign(g,'F',.25,.32,-w/2+2.5,1.75,-d/2+.21,'#ac392d');
// Wheel marks are subtle repeated tracks, not an oversized grid.
for(let i=0;i<12;i++){const x=-w/2+2+(i*7.1)%(w-4),z=-d/2+3+(i*3.7)%(d-6);box(g,.035,.002,1.2,x,.001,z,'#989d97');box(g,.035,.002,1.2,x+.65,.001,z,'#989d97');}batch(g);this.root.add(g);
this.roof=new T.Group();for(let z=-d/2+2;z<d/2;z+=6){box(this.roof,w,.12,.1,0,7.1,z,'#78858e');box(this.roof,w,.12,.1,0,7.8,z,'#78858e');for(let x=-w/2;x<w/2-1;x+=2)rod(this.roof,[x,7.1,z],[x+2,7.8,z],.035,'#77838c');for(const x of [-w*.28,0,w*.28]){box(this.roof,2.1,.1,.28,x,6.88,z,'#545f67');const light=mat('#f1f4e9');light.emissive.set('#f1f4e9');light.emissiveIntensity=2.5;box(this.roof,1.98,.02,.2,x,6.815,z,light);}}
batch(this.roof);const ceiling=add(this.roof,geometry('ceiling',()=>new T.BoxGeometry(1,1,1)),mat('#75828b'),0,8.05,0);ceiling.scale.set(w,.08,d);ceiling.castShadow=false;this.root.add(this.roof);this.frontWalls=new T.Group();box(this.frontWalls,w,h,.16,0,h/2,d/2,'wall');box(this.frontWalls,.16,h,d,-w/2,h/2,0,'wall');batch(this.frontWalls);this.root.add(this.frontWalls);}
updateMode(){this.atmosphere.setInterior(this.mode==='inside');if(this.roof)this.roof.visible=this.mode==='inside';if(this.frontWalls)this.frontWalls.visible=this.mode==='inside';this.ao.enabled=this.mode!=='2d';}
center(mode='3d'){if(!this.project)return;this.mode=mode;this.updateMode();const s=Math.max(this.project.width,this.project.depth),aspect=this.camera.aspect;this.controls.enableRotate=mode!=='2d';if(mode==='inside'){this.camera.position.set(this.project.width*.25,1.75,this.project.depth*.4);this.controls.target.set(this.project.width*.10,2,-this.project.depth*.32);this.camera.fov=65;}else if(mode==='2d'){this.camera.position.set(0,s*1.4*Math.max(1,1/aspect),.01);this.controls.target.set(0,0,0);this.camera.fov=43;}else{this.camera.fov=43;this.controls.target.set(0,1.8,this.project.templateId==='fulfillment'?2:this.project.logisticsYard?10:0);const direction=new T.Vector3(-.85,.68,.99).normalize(),right=new T.Vector3().crossVectors(new T.Vector3(0,1,0),direction).normalize(),up=new T.Vector3().crossVectors(direction,right),tanY=Math.tan(43*Math.PI/360),tanX=tanY*aspect;let distance=0;for(const x of [-this.project.width/2-1,this.project.width/2+1])for(const y of [0,8.2])for(const z of [-this.project.depth/2-1,this.project.depth/2+(this.project.templateId==='fulfillment'?4:this.project.logisticsYard?35:1)]){if(y>0&&x<0&&z>0)continue;const offset=new T.Vector3(x,y,z).sub(this.controls.target);distance=Math.max(distance,offset.dot(direction)+Math.max(Math.abs(offset.dot(right))/tanX,Math.abs(offset.dot(up))/tanY));}this.camera.position.copy(this.controls.target).addScaledVector(direction,distance*(this.project.logisticsYard?1.08:1.22));}this.camera.updateProjectionMatrix();this.ao.setSize(this.container.clientWidth,this.container.clientHeight);this.controls.update();}
focus(id){const o=this.project.objects.find(o=>o.id===id);if(!o)return;this.controls.target.set(o.x,o.h*.45,o.z);if(isEquipment(o.type)){const distance=Math.max(o.w,o.d,o.h)*2.2;this.camera.position.set(o.x-distance*.7,o.h*.45+distance*.55,o.z+distance);this.controls.update();return;}this.camera.position.set(o.x-(o.type==='worker'?2:6),o.type==='worker'?2.2:Math.max(4,o.h+2),o.z+(o.type==='worker'?2.8:7));this.controls.update();}
setMotion(enabled,reset=false){this.motionEnabled=enabled;if(reset){this.motionTime=0;this.animateVehicles();this.animatePeople(true);this.animateTruck();}this.needsRender=true;this.onMotionChange?.();}
animateVehicles(){for(const m of this.movers){const p=routePosition(m.route,this.motionTime),delta=(p.x-m.last.x)*Math.sin(m.object.rotation*Math.PI/180)-(p.z-m.last.z)*Math.cos(m.object.rotation*Math.PI/180);m.group.position.set(p.x,0,p.z);for(const wheel of m.group.userData.wheels||[])wheel.rotateY(-delta/.27);if(m.group.userData.beacon)m.group.userData.beacon.material.emissiveIntensity=.8+3*Math.pow(Math.max(0,Math.sin(this.motionTime*5)),12);m.last=p;}}
animatePeople(reset=false){for(const p of this.people){
 const t=this.motionTime;let pace=0,step=0;
 if(p.route&&!reset){const pos=routePosition(p.route,t),next=routePosition(p.route,t+.03),delta=next[p.route.axis]-pos[p.route.axis];p.group.position.set(pos.x,0,pos.z);pace=Math.min(1,Math.abs(delta)/.0195);step=Math.sin(t*7+p.phase);const heading=p.route.axis==='x'?(delta>=0?Math.PI/2:-Math.PI/2):(delta>=0?0:Math.PI);const diff=Math.atan2(Math.sin(heading-p.group.rotation.y),Math.cos(heading-p.group.rotation.y));p.group.rotation.y+=diff*.12;
 }else if(reset){p.group.position.set(p.object.x,0,p.object.z);p.group.rotation.y=-p.object.rotation*Math.PI/180;}
 animateHuman(p.group,t,pace,p.phase,p.packing,reset);
 }}
animateTruck(){if(!this.yard)return;const state=this.yard.update(this.motionTime);this.onTruckChange?.(state);}
focusTruck(){if(!this.yard)return;const x=Math.min(16,this.project.width/2-4);this.controls.target.set(x,1.5,this.project.depth/2+8);this.camera.position.set(x-14,13,this.project.depth/2+26);this.controls.update();this.needsRender=true;}
setLighting(mode){if(!lightingPresets[mode])return;const p=lightingPresets[mode];this.atmosphere.apply(mode);this.sun.intensity=p.sun;this.sun.color.set(p.sunColor);this.sun.position.set(this.project?.width||36,mode==='golden'?14:32,8);this.ambient.intensity=p.ambient;this.fill.intensity=p.fill;this.scene.environmentIntensity=mode==='night'?.12:.26;this.renderer.toneMappingExposure=p.exposure;this.needsRender=true;}
setQuality(high){this.ao.enabled=high&&this.mode!=='2d';this.renderer.setPixelRatio(Math.min(devicePixelRatio,high?1.75:1));this.resize();}
}
